version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    ports:
      - "8000:8000"
    networks:
      - laravel
    command: >
      sh -c "composer install && php artisan key:generate && php artisan migrate --force && php artisan serve --host=0.0.0.0"

  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: api_laravel
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3399:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
